name: GH Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: install
      run: yarn install
      env:
        CI: true

    - name: Generate changelog
      run: echo "::set-env name=INPUT_BODY::"$(npx conventional-changelog -p angular -r 2)""

    - name: Test Changelog
      run: echo $INPUT_BODY

    # - name: Create Github Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{secrets.DOCS_TOKEN}}
    #   with:
    #     # tag_name: ${{ github.ref }}
    #     # release_name: Release ${{ github.ref }}
    #     tag_name: v0.3.0
    #     release_name: Release v0.3.0
    #     draft: true
    #     prerelease: false
